version: "3.8"

services:
  api:
    container_name: enclave-api
    build: .
    ports:
      - "8005:8005"
    env_file:
      - .env
    healthcheck:
      test: "exit 0"
    depends_on:
      db:
        condition: service_healthy
    networks:
     - enclave-network

  db:
    container_name: enclave-db
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
     - enclave-network
    healthcheck:
      test: "exit 0"

volumes:
  pg_data:
    driver: local

networks:
  enclave-network:
    name: enclave-network
    driver: bridge
